language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t dtakacs/docker-react .

script:
  - docker run -e CI=true dtakacs/docker-react npm run test -- --coverage
